version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "vscode"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99