name: Publish VSCode Extension
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: vscode

      - name: Publish
        working-directory: vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: node_modules/vsce/out/vsce publish